# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  all-go:
    schedule:
      interval: "daily"

  all-docker:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/core" # Location of package manifests
    multi-ecosystem-group: "all-go"
    patterns: [ "*" ]
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/ee-stub" # Location of package manifests
    multi-ecosystem-group: "all-go"
    patterns: [ "*" ]
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/desktop-ce" # Location of package manifests
    multi-ecosystem-group: "all-go"
    patterns: [ "*" ]
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/desktop-common" # Location of package manifests
    multi-ecosystem-group: "all-go"
    patterns: [ "*" ]
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/cli" # Location of package manifests
    multi-ecosystem-group: "all-go"
    patterns: [ "*" ]
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/core"
    multi-ecosystem-group: "all-docker"
    patterns: [ "*" ]
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docs"
    multi-ecosystem-group: "all-docker"
    patterns: [ "*" ]
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
